name: SF-CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install BITO CLI
        run: curl https://alpha.bito.ai/downloads/cli/install.sh -fsSL | bash
      - name: Verify Installation
        run: |
          echo | cd /home/runner/.bitoai/etc/
          echo '{' > /home/runner/.bitoai/etc/session.txt
          echo '  "user": "o2IhzUzVIZsE6wE6IkFL8071JsoXCicMp41E7wMSfDlYn/OY+KPfOA90+zjVjaQ="' >> /home/runner/.bitoai/etc/session.txt
          echo '}' >> /home/runner/.bitoai/etc/session.txt
          echo | ls -la /home/runner/.bitoai/etc/


