name: SF-CI

on:
  push:
    branches: [ feature/* ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "nervill@gmail.com"
          password: "#D13g01808.."
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull the Docker image
        run: docker pull neriovillalobos/delta-robotina:v0.2

      - name: Run the container
        run: |
          docker run --name delta-robotina -d neriovillalobos/delta-robotina:v0.2
          # docker exec delta-robotina python /home/robotina-analize.py ${{ github.ref_name }} main
          git diff --name-only --diff-filter=AMR ${{ github.ref_name }} main

      - name: Stop and remove the container
        run: |
          docker stop delta-robotina
          docker rm delta-robotina

          



