name: SF-CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install BITO CLI
        run: curl https://alpha.bito.ai/downloads/cli/install.sh -fsSL | bash
      - name: Verify Installation
        run: |
          find / -type d -name ".bitoai" 2>/dev/null


