name: SF-CI

on:
  push:
    branches: [ feature/* ]
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verificando Repositorio
        uses: actions/checkout@v2
      
      - name: Acceso a Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "nervill@gmail.com" --password-stdin
      
      - name: Configuracion del Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull de la imagen de Docker
        run: docker pull neriovillalobos/delta-robotina:v0.2

      - name: Ejecución del Contenedor dentro del contenedor de Github
        run: |
          docker run --name delta-robotina -d -v ${{ github.workspace }}:/home/project neriovillalobos/delta-robotina:v0.2

      - name: Revisión del Estado del Contenedor
        run: |
          if [ $(docker inspect -f '{{.State.Running}}' delta-robotina) != "true" ]; then
            echo "Container is not running. Exiting..."
            exit 1
          fi

      - name: Configuracion del directorio seguro para Git
        run: |
          docker exec delta-robotina git config --global --add safe.directory /home/project

      - name: Ejecucion de Analisis de los componentes
        run: |
          docker exec delta-robotina /bin/bash -c '
            cd /home/project &&
            git fetch origin &&
            git checkout main &&
            git pull &&
            git checkout ${{ github.ref_name }} &&
            git pull
            commit_message=""
            git diff --name-only --diff-filter=AMR main ${{ github.ref_name }} > filesAMR.txt
            grep "classes" filesAMR.txt | grep -v "\-meta\.xml$" | while read -r file; do
            commit_message+="## Análisis de Seguridad para $file\n\n"
            commit_message+=$(cat "$file" | gemini-cli prompt "Analiza el siguiente código de un metadato de Salesforce desde el punto de vista de la seguridad para Salesforce. Proporciona una lista resumida exclusivamente de los errores de seguridad de alta prioridad encontrados" embed content -)
            commit_message+="\n\n"
            done
            rm filesAMR.txt
            git config user.name "GitHub Actions Admin"
            git config user.email "nervill@gmail.com"
            git commit --allow-empty -m "Seguridad: Análisis completado para ${{ github.ref_name }}\n\n$commit_message"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/NerioVillalobos/sfdeploypipeline.git
          '

      - name: Deteniendo y Eliminando el Contenedor
        if: always()
        run: |
          docker stop delta-robotina
          docker rm delta-robotina
