name: SF-CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Aquí especifica el distribuidor de JDK, por ejemplo, 'adopt', 'adopt-openj9', etc.

      - name: Run PMD Salesforce Security Check
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.41.0/pmd-bin-6.41.0.zip
          unzip pmd-bin-6.41.0.zip
          cd pmd-bin-6.41.0/bin
          set -x  # Activar modo verbose
          ./run.sh pmd -d ./*.cls -f text -R scripts/salesforce-rules.xml > pmd_salesforce_report.txt 2>&1
          cat pmd_salesforce_report.txt

