name: SF-CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "nervill@gmail.com"
          password: "#D13g01808.."
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull the Docker image
        run: docker pull neriovillalobos/delta-robotina:v0.2

      - name: Run the container
        run: docker run neriovillalobos/delta-robotina:v0.2

          



