name: SF-CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install BITO CLI
        run: curl https://alpha.bito.ai/downloads/cli/install.sh -fsSL | bash
      - name: Verify Installation
        run: |
          cd /home/runner/.bitoai/etc/
          echo '{' > session.txt
          echo '  "user": "o2IhzUzVIZsE6wE6IkFL8071JsoXCicMp41E7wMSfDlYn/OY+KPfOA90+zjVjaQ="' >> session.txt
          echo '}' >> session.txt
          ls -la /home/runner/.bitoai/etc/
          echo 'bito:' > bito-cli.yaml
          echo '  access_key: eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjoidjFfNjI3NV84OTIzNzBfNTY3MjgzX1R1ZSBKdW4gMTEgMTc6MzQ6MTEgVVRDIDIwMjQifQ.i2dJ7UEbIcMWXzHYLZ7lVuOaqiMhsY5CTnj06BL5cd0' >> bito-cli.yaml
          echo '  email: nerio.villalobos@nespon.com' >> bito-cli.yaml
          echo '  preferred_ai_model: BASIC' >> bito-cli.yaml
          echo 'settings:' >> bito-cli.yaml
          echo '    auto_update: true' >> bito-cli.yaml
          echo '    max_context_entries: 20' >> bito-cli.yaml
          ls -la /home/runner/.bitoai/etc/
