name: SF-CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: neriovillalobos/delta-robotina:v0.2

    steps:
      - uses: actions/checkout@v2

          



