name: SF-CI

on:
  push:
    branches: [ feature/* ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verificando Repositorio
        uses: actions/checkout@v2
      
      - name: Acceso a Docker Hub
        uses: docker/login-action@v2
        with:
          username: "nervill@gmail.com"
          password: "#D13g01808.."
      
      - name: Configuracion del Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull de la imagen de Docker
        run: docker pull neriovillalobos/delta-robotina:v0.2

      - name: Ejecuci贸n del Contenedor dentro del contenedor de Github
        run: |
          docker run --name delta-robotina -d -v ${{ github.workspace }}:/home/project neriovillalobos/delta-robotina:v0.2

      - name: Revisi贸n del Estado del Contenedor
        run: |
          if [ $(docker inspect -f '{{.State.Running}}' delta-robotina) != "true" ]; then
            echo "Container is not running. Exiting..."
            exit 1
          fi

      - name: Configuraci贸n del directorio seguro para Git
        run: |
          docker exec delta-robotina git config --global --add safe.directory /home/project

      - name: Ejecucion de Analisis de los componentes
        run: |
          docker exec delta-robotina /bin/bash -c "
            cd /home/project &&
            git fetch origin &&
            git checkout main &&
            git pull &&
            git checkout ${{ github.ref_name }} &&
            git pull &&
            touch security_analysis.txt
            ls -la
            grep "classes" security_analysis.txt | while IFS= read -r line; do echo "Resultado para $line:"; cat "$line" | gemini-cli prompt "Analiza el siguiente c贸digo de un metadato de Salesforce desde el punto de vista de la seguridad para Salesforce. Proporciona una lista resumida de exclusivamente de los errores de seguridad de alta prioridad encontrados:"; echo ""; done
            ls -la
            cat security_analysis.txt
            "

      - name: Deteniendo y Eliminando el Contenedor
        if: always()
        run: |
          docker stop delta-robotina
          docker rm delta-robotina

      - name: Carga del Analisis de Seguridad
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security_analysis
          path: /home/project/security_analysis.txt
