name: SF-CI

on:
  push:
    branches: [ feature/* ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "nervill@gmail.com"
          password: "#D13g01808.."
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull the Docker image
        run: docker pull neriovillalobos/delta-robotina:v0.2

      - name: Run the container
        run: |
          docker run --name delta-robotina -d -v ${{ github.workspace }}:/home/project neriovillalobos/delta-robotina:v0.2

      - name: Check container status
        run: |
          if [ $(docker inspect -f '{{.State.Running}}' delta-robotina) != "true" ]; then
            echo "Container is not running. Exiting..."
            exit 1
          fi

      - name: Execute analysis script
        run: |
          docker exec delta-robotina /bin/bash -c "
            cd /home/project &&
            git fetch origin &&
            git checkout ${{ github.ref_name }} &&
            python /home/robotina-analize.py ${{ github.ref_name }} main
          "

      - name: Stop and remove the container
        if: always()
        run: |
          docker stop delta-robotina
          docker rm delta-robotina

      - name: Upload security analysis
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security_analysis
          path: /home/project/security_analysis.txt
