name: SF-CI

on:
  push:
    branches: [ feature/* ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Acceso a Docker Hub
        uses: docker/login-action@v2
        with:
          username: "nervill@gmail.com"
          password: "#D13g01808.."
      
      - name: Configuracion del Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull de la imagen de Docker
        run: docker pull neriovillalobos/delta-robotina:v0.2

      - name: Ejecución del Contenedor
        run: |
          docker run --name delta-robotina -d -v ${{ github.workspace }}:/home/project neriovillalobos/delta-robotina:v0.2

      - name: Revisión del Estado del Contenedor
        run: |
          if [ $(docker inspect -f '{{.State.Running}}' delta-robotina) != "true" ]; then
            echo "Container is not running. Exiting..."
            exit 1
          fi

      - name: Configuración del directorio seguro para Git
        run: |
          docker exec delta-robotina git config --global --add safe.directory /home/project

      - name: Ejecucion de Analisis de los componentes
        run: |
          docker exec delta-robotina /bin/bash -c "
            cd /home/project &&
            git fetch origin &&
            git checkout main &&
            git pull &&
            git checkout ${{ github.ref_name }} &&
            git pull &&
            git diff --name-only ${{ github.ref_name }} main > filesAMR.txt &&
            ls -la &&
            cat filesAMR.txt
            rm -rf force-app/
            rm -rf filesAMR.txt
            touch security_analysis.txt
            chmod 664 security_analysis.txt 
            cp /home/robotina-analize.py /home/project/
            ls -la
            python robotina-analize.py ${{ github.ref_name }} main
            ls -la
            cat filesAMR.txt
            ls -la
            tree force-app/
            ls -la
            cat security_analysis.txt
            "

      - name: Deteniendo y Eliminando el Contenedor
        if: always()
        run: |
          docker stop delta-robotina
          docker rm delta-robotina

      - name: Upload security analysis
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security_analysis
          path: /home/project/security_analysis.txt
