name: SF-CI

on:
  push:
    branches: [ feature/* ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "nervill@gmail.com"
          password: "#D13g01808.."
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull the Docker image
        run: docker pull neriovillalobos/delta-robotina:v0.2

      - name: Run the container in foreground
        id: run_container
        run: |
          docker run --name delta-robotina -v ${{ github.workspace }}:/home/project neriovillalobos/delta-robotina:v0.2
          docker logs delta-robotina || true

      - name: Debug container
        if: always()
        run: |
          docker run -it --name delta-robotina-debug -v ${{ github.workspace }}:/home/project neriovillalobos/delta-robotina:v0.2 /bin/bash || true
          docker logs delta-robotina-debug || true

      - name: Stop and remove the container
        if: always()
        run: |
          docker stop delta-robotina || true
          docker rm delta-robotina || true
          docker stop delta-robotina-debug || true
          docker rm delta-robotina-debug || true

      - name: Upload security analysis
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security_analysis
          path: /home/project/security_analysis.txt
