name: SF-CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Aquí especifica el distribuidor de JDK, por ejemplo, 'adopt', 'adopt-openj9', etc.

      - name: Run PMD Salesforce Security Check
        run: |
          ls -la ./  # Lista el contenido del directorio actual para diagnóstico
          ./pmd-bin-6.41.0/bin/run.sh pmd -d ./Apirest.cls -f text -R scripts/salesforce-rules.xml > pmd_salesforce_report.txt 2>&1
          cat pmd_salesforce_report.txt


