# ------------------------------------------------------------------------------
# Nombre del Pipeline: Deploy on push - SIT
# Proyecto: Testing
# Descripción: Prueba de nuevo contenedor
# Creado por: Nerio Villalobos  (nervill@gmail.com)
# Fecha de creación: 07/05/2025
# ------------------------------------------------------------------------------

name: SF-CI

on:
  push:
    branches: [ feature/* ]
  workflow_dispatch:

jobs:
  dev-deploy-pr-on-push:
    runs-on: 
      ubuntu-latest
    container:
      neriovillalobos/delta-robotina:v0.4
      
    
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4.2.1

      - name: Extracting private key
        run: echo "${{ secrets.JWT_SERVER_KEY }}" > $GITHUB_WORKSPACE/server.key

      - name: enviroment login
        shell: bash
        run: |
          sf org login jwt \
          --jwt-key-file "$GITHUB_WORKSPACE/server.key" \
          --client-id ${{ secrets.CKEY }} \
          --username ${{ secrets.DEVOPS_USERNAME }} \
          --instance-url ${{ vars.DEV_NERVILL }}
      
      - name: Validar clases Apex desde package.xml
        shell: bash
        run: |
          set -euo pipefail
          cd "$GITHUB_WORKSPACE"

          echo "🧪 Iniciando revisión del package.xml..."

          HAS_MEMBERS=$(xmllint --xpath "count(//Package/types/members)" manifest/package.xml 2>/dev/null || echo "0")

          if [[ "$HAS_MEMBERS" -eq 0 ]]; then
          echo "🚫 El package.xml no contiene ningún componente (<members>). No hay nada para desplegar."
          exit 1
          fi

          echo "🔍 Se detectaron $HAS_MEMBERS componentes en el package.xml."

          BLOCKS=$(xmllint --xpath "//Package/types" manifest/package.xml 2>/dev/null || echo "")

          echo "$BLOCKS" | tr '\n' ' ' | \
          sed 's#</types>#\n#g' | grep "<name>ApexClass</name>" | \
          sed -n 's/.*<members>\(.*\)<\/members>.*/\1/p' > apex_classes.txt || true

          if [[ -s apex_classes.txt ]]; then
          echo "✅ Clases Apex detectadas:"
          cat apex_classes.txt
          else
          echo "ℹ️ No hay ApexClass en el package.xml. Probablemente contiene otros componentes."
          fi

          rm -f apex_classes.txt


      - name: Clean up private key
        if: always()
        run: rm -f server.key