# ------------------------------------------------------------------------------
# Nombre del Pipeline: Deploy on push - SIT
# Proyecto: Testing
# Descripción: Prueba de nuevo contenedor
# Creado por: Nerio Villalobos  (nervill@gmail.com)
# Fecha de creación: 07/05/2025
# ------------------------------------------------------------------------------

name: SF-CI

on:
  push:
    branches: [ feature/* ]
  workflow_dispatch:

jobs:
  dev-deploy-pr-on-push:
    runs-on: 
      ubuntu-latest
    container:
      neriovillalobos/delta-robotina:v0.4
      
    
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4.2.1

      - name: Extracting private key
        run: echo "${{ secrets.JWT_SERVER_KEY }}" > $GITHUB_WORKSPACE/server.key

      - name: enviroment login
        shell: bash
        run: |
          sf org login jwt \
          --jwt-key-file "$GITHUB_WORKSPACE/server.key" \
          --client-id ${{ secrets.CKEY }} \
          --username ${{ secrets.DEVOPS_USERNAME }} \
          --instance-url ${{ vars.DEV_NERVILL }}
      
      - name: Validate Deploy Core Components
        shell: bash
        run: |
          set -euo pipefail
          cd "$GITHUB_WORKSPACE"

          echo "🧪 Iniciando revisión del package.xml..."

          if xmllint --xpath "boolean(//Package/types[name='ApexClass']/members)" manifest/package.xml; then
          echo "✅ Se encontraron ApexClass. Extrayendo contenido..."

          RAW_XML=$(xmllint --xpath "//Package/types[name='ApexClass']/members" manifest/package.xml 2>/dev/null || true)

          if [[ -z "$RAW_XML" ]]; then
          echo "❌ No se pudo extraer los miembros de ApexClass. Abortando."
          exit 1
          fi

          echo "$RAW_XML" | sed -E 's|</?members>|\n|g' | grep -v '^$' > apex_classes.txt

          echo "🧾 Clases Apex detectadas:"
          cat apex_classes.txt

          rm -f apex_classes.txt
          else
          echo "⚠️ No se encontraron ApexClass en el package.xml."
          fi

      - name: Clean up private key
        if: always()
        run: rm -f server.key